include: package:flutter_lints/flutter.yaml

# Loosen a few noisy rules to keep "flutter analyze" green while we refactor.
analyzer:
  errors:
    # Allow temporary prints during development without failing the analyze step.
    avoid_print: ignore
    # Flutter 3.27+ deprecations we will migrate gradually.
    deprecated_member_use: ignore
    # Common in async UI flows; guarded by mounted checks in code.
    use_build_context_synchronously: ignore
    # Internal private types surfaced via charts/widgets – safe to ignore for now.
    library_private_types_in_public_api: ignore
    # Style nits shouldn't fail CI.
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true


